force-app/main/default/objects/Geo_Coding_Auth_Setting__mdt/Geo_Coding_Auth_Setting__mdt.object-meta.xml
<CustomObject>
    <description>API settings for Geo Coding Service</description>
    <label>Geo Coding Auth Setting</label>
    <pluralLabel>Geo Coding Auth Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Geo_Coding_Auth_Setting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>API Key for Geo Coding Service</description>
    <inlineHelpText>API Key for Geo Coding Service</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Geo_Coding_Auth_Setting__mdt/fields/Hostname__c.field-meta.xml
<CustomField>
    <fullName>Hostname__c</fullName>
    <description>Hostname of the geo coding service.</description>
    <inlineHelpText>Hostname of the geo coding service.</inlineHelpText>
    <label>Hostname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Zipcode_Search__mdt/One_Degree_Zipcode_Search__mdt.object-meta.xml
<CustomObject>
    <description>This will store the zip codes along with latitude and longitude of the zip codes.</description>
    <label>One Degree Zipcode Search</label>
    <pluralLabel>One Degree Zipcodes Search</pluralLabel>
</CustomObject>

force-app/main/default/objects/One_Degree_Zipcode_Search__mdt/fields/lat__c.field-meta.xml
<CustomField>
    <fullName>lat__c</fullName>
    <description>DO NOT USE</description>
    <inlineHelpText>DO NOT USE</inlineHelpText>
    <label>lat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Zipcode_Search__mdt/fields/long__c.field-meta.xml
<CustomField>
    <fullName>long__c</fullName>
    <description>Longitude of the zipcode.</description>
    <inlineHelpText>Longitude of the zipcode.</inlineHelpText>
    <label>long</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Zipcode_Search__mdt/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <description>Store zipcode to search providers.</description>
    <inlineHelpText>Store zipcode to search providers.</inlineHelpText>
    <label>Zipcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GeoCodingServiceQueueable.cls
global class GeoCodingServiceQueueable implements Queueable, Database.AllowsCallouts {

    Set<String> querySet = new Set<String>();
    Map<String, String> authSet = new Map<String, String>();
    
    global GeoCodingServiceQueueable() {
        Geo_Coding_Auth_Setting__mdt geoSetting = [SELECT MasterLabel, DeveloperName, 
                                                    API_Key__c ,Hostname__c
                                                    FROM Geo_Coding_Auth_Setting__mdt LIMIT 1];
        authSet.put('API_Key__c', geoSetting.API_Key__c);
        authSet.put('Hostname__c', geoSetting.Hostname__c);                
    }
    
    global void execute(QueueableContext context) {
		string queryserviceZipCodes = 'SELECT Id, MasterLabel, DeveloperName, Zipcode__c, lat__c, long__c FROM One_Degree_Zipcode_Search__mdt ORDER BY Zipcode__c';
		List<One_Degree_Zipcode_Search__mdt> serviceZipCodes = new CustomMetadataDAO().getCustomMetadataRecords(queryserviceZipCodes);        

        for(One_Degree_Zipcode_Search__mdt serviceZipCode : serviceZipCodes) {
            String query = authSet.get('Hostname__c') + '?address=' + serviceZipCode.Zipcode__c + '&key=' + authSet.get('API_Key__c');
            querySet.add(query);
        }
        List<String> queryParams = new List<String>();
        for(String s : querySet) {
            System.debug(LoggingLevel.DEBUG, '---> query url ' + s);
            queryParams.add(s);
        }                
        if(!System.isFuture()) {
            System.debug(LoggingLevel.DEBUG, '---> processing Geo Coding service - start.');
            GeoCodingService.processGeoCodingService(authSet, queryParams);
            System.debug(LoggingLevel.DEBUG, '---> processing Geo Coding service - end.');            
        }        
    }
}