force-app/main/default/objects/OD_Search_Area__c/OD_Search_Area__c.object-meta.xml
<CustomObject>
    <description>Keywords to use for full text searching. This is the top-level parameter whose value is the set of search parameters</description>
    <label>OD Search Area</label>
    <nameField>
        <displayFormat>ODS-{0000}</displayFormat>
        <label>OD Search Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OD Search Areas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OD_Search_Area__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>One degree search area query parameter.</description>
    <inlineHelpText>One degree search area query parameter.</inlineHelpText>
    <label>Area</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Urgent!</fullName>
            </value>
            <value>
                <fullName>Family &amp; Household</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OD_Search_Area__c/fields/Job_EndDate__c.field-meta.xml
<CustomField>
    <fullName>Job_EndDate__c</fullName>
    <defaultValue></defaultValue>
    <description>End date of the job</description>
    <inlineHelpText>End date of the job</inlineHelpText>
    <label>Job Enddate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OD_Search_Area__c/fields/Job_StartDate__c.field-meta.xml
<CustomField>
    <fullName>Job_StartDate__c</fullName>
    <defaultValue></defaultValue>
    <description>Start date of the job</description>
    <inlineHelpText>Start date of the job</inlineHelpText>
    <label>Job Startdate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OD_Search_Area__c/fields/OD_Zipcode__c.field-meta.xml
<CustomField>
    <fullName>OD_Zipcode__c</fullName>
    <description>This is child of the OD zipcode object.</description>
    <inlineHelpText>This is child of the OD zipcode object.</inlineHelpText>
    <label>OD Zipcode</label>
    <referenceTo>OD_Zipcode__c</referenceTo>
    <relationshipLabel>OD Search Areas</relationshipLabel>
    <relationshipName>OD_Search_Areas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OD_Search_Area__c/fields/Program_Area__c.field-meta.xml
<CustomField>
    <fullName>Program_Area__c</fullName>
    <description>Map the corresponding Program Area Type to One Degree Area.</description>
    <inlineHelpText>Map the corresponding Program Area Type to One Degree Area.</inlineHelpText>
    <label>Program Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Care</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Money</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>Work</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OD_Zipcode__c/OD_Zipcode__c.object-meta.xml
<CustomObject>
    <label>OD Zipcode</label>
    <nameField>
        <displayFormat>ODZ-{00000}</displayFormat>
        <label>OD Zipcode Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OD Zipcodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OD_Zipcode__c/fields/Distance__c.field-meta.xml
<CustomField>
    <fullName>Distance__c</fullName>
    <defaultValue>10</defaultValue>
    <description>The radius in kilometers around the coordinates specified in which to search. Ref https://github.com/1deg/resource-server-api-docs/blob/master/docs/common/query.md</description>
    <inlineHelpText>The radius in kilometers around the coordinates specified in which to search.</inlineHelpText>
    <label>Distance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OD_Zipcode__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <description>Latitude</description>
    <inlineHelpText>Latitude</inlineHelpText>
    <label>Latitude</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OD_Zipcode__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <description>Longitude</description>
    <inlineHelpText>Longitude</inlineHelpText>
    <label>Longitude</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OD_Zipcode__c/fields/Results__c.field-meta.xml
<CustomField>
    <fullName>Results__c</fullName>
    <defaultValue>30</defaultValue>
    <description>Number of results returned from the API.</description>
    <inlineHelpText>Number of results returned from the API.</inlineHelpText>
    <label>Results</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OD_Zipcode__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <description>Zipcode</description>
    <inlineHelpText>Zipcode</inlineHelpText>
    <label>Zipcode</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/One_Degree_Auth_Setting__mdt/One_Degree_Auth_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This will store the API Key and Hostname for one degree service provider.</description>
    <label>One Degree Auth Setting</label>
    <pluralLabel>One Degree Auth Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/One_Degree_Auth_Setting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>This will store the API Key for One degree services.</description>
    <inlineHelpText>This will store the API Key for One degree services.</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Auth_Setting__mdt/fields/Hostname__c.field-meta.xml
<CustomField>
    <fullName>Hostname__c</fullName>
    <description>Hostname for One Degree Service.</description>
    <inlineHelpText>Hostname for One Degree Service.</inlineHelpText>
    <label>Hostname</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OneDegreeServiceBatchable.cls
global with sharing class OneDegreeServiceBatchable implements 
            Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    // instance member to retain state across transactions
    public Integer recordsProcessed = 0; 
    public Integer totalBatchProcessed = 0; 
    public Map<Id, List<Datetime>> logJobTimes = new Map<Id, List<Datetime>>();
    Map<String, String> querySet = new Map<String, String>();
    Map<String, String> authSet = new Map<String, String>();

    global OneDegreeServiceBatchable() {
        One_Degree_Auth_Setting__mdt odSetting = [SELECT MasterLabel, DeveloperName, 
                                                    API_Key__c ,Hostname__c
                                                    FROM One_Degree_Auth_Setting__mdt LIMIT 1];
        authSet.put('API_Key__c', odSetting.API_Key__c);
        authSet.put('Hostname__c', odSetting.Hostname__c);        
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String dateTimeFormat = DateTime.now().formatGMT('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'');
        System.debug(LoggingLevel.DEBUG, 'Date Criteria : ' + dateTimeFormat);
        return Database.getQueryLocator(
            'SELECT Id, Name, Area__c, Program_Area__c, Job_StartDate__c, OD_Zipcode__c, ' +
            'OD_Zipcode__r.Id, OD_Zipcode__r.Results__c, OD_Zipcode__r.Zipcode__c, ' +
            'OD_Zipcode__r.Latitude__c, OD_Zipcode__r.Longitude__c, OD_Zipcode__r.Distance__c, ' +
            'Job_EndDate__c FROM OD_Search_Area__c WHERE (Job_StartDate__c <= ' + dateTimeFormat + 
            ' OR Job_StartDate__c = null) ' +
            'ORDER BY Job_StartDate__c ASC'
        );
    }
    
    global void execute(Database.BatchableContext bc, List<OD_Search_Area__c> scope){

        Integer totalCallouts = Limits.getLimitCallouts();
        List<Datetime> jobTimes = new List<Datetime>();
        for(OD_Search_Area__c area : scope) {
            Datetime startDateTime = Datetime.now(); // returns date time value in GMT time zone.
            //Integer offsetStart = UserInfo.getTimezone().getOffset(startDateTime);
            //Datetime startTime = startDateTime.addSeconds(offsetStart/1000);

            jobTimes.add(startDateTime);
            recordsProcessed++;
            System.debug(Logginglevel.DEBUG, '---> lat ' + area.OD_Zipcode__r.Latitude__c);
            System.debug(Logginglevel.DEBUG, '---> zipcode ' + area.OD_Zipcode__r.Zipcode__c);
            Map<string, SearchParams> searchParamsList = getQueryString(area.OD_Zipcode__r, area);
            System.debug(Logginglevel.DEBUG, searchParamsList);

            for(SearchParams val : searchParamsList.values()) {
                System.debug(LoggingLevel.DEBUG, '---> val ' + val.zipcode + ',' + val.area + ',' + 
                                            val.latitude + ',' + val.longitude);
                if(searchParamsList.size() > 0) {
                    for(SearchParams s : searchParamsList.values()) {
                            String query = authSet.get('Hostname__c') + 
                                            'opportunities?api_key='+ authSet.get('API_Key__c') +
                                            '&query[lat]='+s.latitude + 
                                            '&query[long]='+s.longitude + 
                                            '&query[text]='+s.area + 
                                            '&query[distance]=' + s.distance + 
                                            '&per_page=' + s.results;
                            querySet.put(query, s.program_area); 
                    } //end of for statement
                } //end of if statement
                Map<String, String> queryParams = new Map<String, String>();
                for(String s : querySet.keySet()) {
                    string program_area = querySet.get(s);
                    System.debug(LoggingLevel.DEBUG, '---> query url ' + s + ', program area ' + program_area);
                    queryParams.put(s, program_area);
                }
                System.debug(LoggingLevel.DEBUG, '---> processing One Degree service - start.');
                ServiceProviderClient.processOneDegreeService(authSet, queryParams);
                Datetime endDateTime = System.Datetime.now(); // returns date time value in GMT time zone.
                jobTimes.add(endDateTime);
                logJobTimes.put(area.Id, jobTimes);
                System.debug(LoggingLevel.DEBUG, '---> processing One Degree service - end.');                                            
            } // end of for statement
        }
        totalBatchProcessed++;
    }
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. Shazam!');
        System.debug(totalBatchProcessed + ' batch processed. Shazam!');
        List<OD_Search_Area__c> records = new List<OD_Search_Area__c>();
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors,
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        for(Id recordId : logJobTimes.keySet()) {
            List<Datetime> jobTimes = logJobTimes.get(recordId);
            System.debug(LoggingLevel.DEBUG, '---> Id ' + recordId);
            System.debug(LoggingLevel.DEBUG, '---> startTime ' + jobTimes[0]);
            System.debug(LoggingLevel.DEBUG, '---> endTime ' + jobTimes[1]);
            OD_Search_Area__c record = new OD_Search_Area__c();
            record.Id = recordId;
            record.Job_StartDate__c = jobTimes[0].addHours(2); //adding or subtracting to datetime is N/24
            record.Job_EndDate__c = jobTimes[1].addHours(2);
            records.add(record);
        }
        Database.SaveResult[] srList = Database.update(records, false);
        // Iterate through each returned result
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully update. ID: ' + sr.getId());
            }else {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
        }
        //check for records that need to be processed.
        //Database.executeBatch(new OneDegreeServiceBatchable(),1);
        // call some utility to send email
        //EmailUtils.sendMessage(job, recordsProcessed);
    } 
    
    private Map<string, SearchParams> getQueryString(OD_Zipcode__c zipcode, OD_Search_Area__c area) {
	    Set<String> querySet = new Set<String>();
		Set<Id> zipcodeIds = new Set<Id>();
        Map<string, SearchParams> zipcodeList = new Map<string, SearchParams>();
        Map<string, SearchParams> searchParamsList = new Map<string, SearchParams>();
        
        zipcodeIds.add(zipcode.Id);
		SearchParams zipcodeParams = new SearchParams();
        zipcodeParams.guid = zipcode.Id;
        zipcodeParams.zipcode = zipcode.Zipcode__c;
        zipcodeParams.latitude = zipcode.Latitude__c;
        zipcodeParams.longitude = zipcode.Longitude__c;
        zipcodeParams.distance = zipcode.Distance__c;
        zipcodeParams.results = zipcode.Results__c;
        zipcodeList.put(zipcode.Id, zipcodeParams);
        System.debug(zipcode.Zipcode__c);

        SearchParams s = zipcodeList.get(area.OD_Zipcode__c);
        if(s.guid != null) {
			SearchParams areaSearchParams = new SearchParams();
            areaSearchParams.guid = area.Id;
            areaSearchParams.zipcode = s.zipcode;
            areaSearchParams.latitude = s.latitude;
            areaSearchParams.longitude = s.longitude;
            areaSearchParams.distance = s.distance;
            areaSearchParams.results = s.results;
            areaSearchParams.area = area.Area__c;
            areaSearchParams.program_area = area.Program_Area__c;
            searchParamsList.put(area.Id, areaSearchParams);
        }else {
            System.debug(LoggingLevel.DEBUG, '---> Error : No Zipcode');
        }
        if(searchParamsList.size() > 0) {
            System.debug(LoggingLevel.DEBUG, '---> search params size ' + searchParamsList.size());
            return searchParamsList;
        }
        return null;
    }    
}