force-app/main/default/objects/One_Degree_API_Key__mdt/One_Degree_API_Key__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata stores a) Google API keys for populating latitude and longitude in the zipcode record. b) One Degree API key for populating referral programs.
Populating the API keys are required before running any jobs.</description>
    <label>One Degree API Key</label>
    <pluralLabel>One Degree API Keys</pluralLabel>
</CustomObject>

force-app/main/default/objects/One_Degree_API_Key__mdt/fields/Google_API_Key__c.field-meta.xml
<CustomField>
    <fullName>Google_API_Key__c</fullName>
    <description>Insert Google API Key here</description>
    <inlineHelpText>Insert Google API Key here</inlineHelpText>
    <label>Google API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/One_Degree_API_Key__mdt/fields/OneDegree_API_Key__c.field-meta.xml
<CustomField>
    <fullName>OneDegree_API_Key__c</fullName>
    <description>Insert OneDegree API Key here</description>
    <inlineHelpText>Insert OneDegree API Key here</inlineHelpText>
    <label>OneDegree API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UpsertAPIKeys.cls
public with sharing class UpsertAPIKeys {
    @AuraEnabled    
    public static String upsertAPIKeysOnSave(String googleAPIKey, String  oneDegreeAPIKey) {
        String result = 'Submitted';

        List<One_Degree_API_Key__mdt> apiKeysList = new List<One_Degree_API_Key__mdt>();        
        
        String query = 'SELECT Id, MasterLabel, NamespacePrefix,DeveloperName,Google_API_Key__c, OneDegree_API_Key__c FROM One_Degree_API_Key__mdt';
        CustomMetadataDAO odAPI = new CustomMetadataDAO();
        List<One_Degree_API_Key__mdt> apiKeys = odAPI.getCustomMetadataRecords(query);            
        
        One_Degree_API_Key__mdt data = new One_Degree_API_Key__mdt();
        try{
            System.debug(' Id ' + apiKeys[0].Id);
            data.Id = apiKeys[0].Id;
            data.Google_API_Key__c = googleAPIKey;
            data.OneDegree_API_Key__c = oneDegreeAPIKey;
            data.DeveloperName = apiKeys[0].DeveloperName;
            data.MasterLabel = apiKeys[0].MasterLabel;
            
            apiKeysList.add(data);
            result = MetaDataUtility.upsertMetadata(apiKeysList);            
        }catch(Exception ex){
            System.debug(LoggingLevel.ERROR, 'Error Message : ' + ex.getMessage());
            System.debug(LoggingLevel.ERROR, 'Error Cause : ' + ex.getCause());
        }
        return result;
    }
}