force-app/main/default/objects/One_Degree_Attribute_Setting__mdt/One_Degree_Attribute_Setting__mdt.object-meta.xml
<CustomObject>
    <description>DO NOT USE</description>
    <label>One Degree Attribute Setting</label>
    <pluralLabel>One Degree Attribute Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/One_Degree_Attribute_Setting__mdt/fields/Attribute_Tag__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Tag__c</fullName>
    <description>DO NOT USE</description>
    <inlineHelpText>DO NOT USE</inlineHelpText>
    <label>Attribute Tag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Attribute_Setting__mdt/fields/Last_Run_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Datetime__c</fullName>
    <label>Last Run Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Test_CustomMetadataDAO.cls
@IsTest
public class Test_CustomMetadataDAO {
    static testMethod void getTestMetadata() {
        List<SObject> customMetadataRecords;
        string query = 'SELECT Id, MasterLabel, DeveloperName, Attribute_Tag__c, Last_Run_Datetime__c ' +
							'FROM One_Degree_Attribute_Setting__mdt ' +
							'LIMIT 1';
        Test.startTest();
        customMetadataRecords = new CustomMetadataDAO().getCustomMetadataRecords(query);
        Test.stopTest();
        System.assertEquals([SELECT Id, MasterLabel FROM One_Degree_Attribute_Setting__mdt LIMIT 1].size(), 
                           customMetadataRecords.size(), 'Size should be equal');
    }    
    public static void setMetadata(string query, List<SObject> records) {
        CustomMetadataDAO.customMetadataRecordsMap.put(query, records);
    }    
}