force-app/main/default/objects/One_Degree_Attribute_Setting__mdt/One_Degree_Attribute_Setting__mdt.object-meta.xml
<CustomObject>
    <description>DO NOT USE</description>
    <label>One Degree Attribute Setting</label>
    <pluralLabel>One Degree Attribute Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/One_Degree_Attribute_Setting__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Search attribute query text.</description>
    <inlineHelpText>Search attribute query text.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/One_Degree_Attribute_Setting__mdt/fields/Attribute_Tag__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Tag__c</fullName>
    <description>DO NOT USE</description>
    <inlineHelpText>DO NOT USE</inlineHelpText>
    <label>Attribute Tag</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Attribute_Setting__mdt/fields/Last_Run_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Last_Run_Datetime__c</fullName>
    <label>Last Run Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/One_Degree_Auth_Setting__mdt/One_Degree_Auth_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This will store the API Key and Hostname for one degree service provider.</description>
    <label>One Degree Auth Setting</label>
    <pluralLabel>One Degree Auth Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/One_Degree_Auth_Setting__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <description>This will store the API Key for One degree services.</description>
    <inlineHelpText>This will store the API Key for One degree services.</inlineHelpText>
    <label>API Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Auth_Setting__mdt/fields/Hostname__c.field-meta.xml
<CustomField>
    <fullName>Hostname__c</fullName>
    <description>Hostname for One Degree Service.</description>
    <inlineHelpText>Hostname for One Degree Service.</inlineHelpText>
    <label>Hostname</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Zipcode_Search__mdt/One_Degree_Zipcode_Search__mdt.object-meta.xml
<CustomObject>
    <description>This will store the zip codes along with latitude and longitude of the zip codes.</description>
    <label>One Degree Zipcode Search</label>
    <pluralLabel>One Degree Zipcodes Search</pluralLabel>
</CustomObject>

force-app/main/default/objects/One_Degree_Zipcode_Search__mdt/fields/lat__c.field-meta.xml
<CustomField>
    <fullName>lat__c</fullName>
    <description>DO NOT USE</description>
    <inlineHelpText>DO NOT USE</inlineHelpText>
    <label>lat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Zipcode_Search__mdt/fields/long__c.field-meta.xml
<CustomField>
    <fullName>long__c</fullName>
    <description>Longitude of the zipcode.</description>
    <inlineHelpText>Longitude of the zipcode.</inlineHelpText>
    <label>long</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/One_Degree_Zipcode_Search__mdt/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <description>Store zipcode to search providers.</description>
    <inlineHelpText>Store zipcode to search providers.</inlineHelpText>
    <label>Zipcode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OneDegreeServiceQueueable.cls
global class OneDegreeServiceQueueable implements Queueable, Database.AllowsCallouts {

    Set<String> querySet = new Set<String>();
    Map<String, String> authSet = new Map<String, String>();

    global OneDegreeServiceQueueable() {
        One_Degree_Auth_Setting__mdt odSetting = [SELECT MasterLabel, DeveloperName, 
                                                    API_Key__c ,Hostname__c
                                                    FROM One_Degree_Auth_Setting__mdt LIMIT 1];
        authSet.put('API_Key__c', odSetting.API_Key__c);
        authSet.put('Hostname__c', odSetting.Hostname__c);        

    }

    global void execute(QueueableContext context) {

        //get all attribute tags
        string queryAttributeTags = 'SELECT Id, MasterLabel, DeveloperName, Attribute_Tag__c, Last_Run_Datetime__c ' +
            							'FROM One_Degree_Attribute_Setting__mdt WHERE Active__c = true ' +
            							'LIMIT 1';
		One_Degree_Attribute_Setting__mdt[] attributeTags = new CustomMetadataDAO().getCustomMetadataRecords(queryAttributeTags);	        
		// get service zipcodes from metadata 
		string queryserviceZipCodes = 'SELECT Zipcode__c, lat__c, long__c ' +
											'FROM One_Degree_Zipcode_Search__mdt ' +
											'WHERE lat__c != null ' +
            								'AND long__c != null';
		List<One_Degree_Zipcode_Search__mdt> serviceZipCodes = new CustomMetadataDAO().getCustomMetadataRecords(queryserviceZipCodes);        

        for(One_Degree_Zipcode_Search__mdt serviceZipCode : serviceZipCodes) {
            String query = authSet.get('Hostname__c') + '/opportunities?api_key='+ authSet.get('API_Key__c') +
                                '&query[lat]='+serviceZipCode.lat__c + '&query[long]='+serviceZipCode.long__c + '&query[distance]=10&per_page=100';
            querySet.add(query);
        }
        List<String> queryParams = new List<String>();
        for(String s : querySet) {
            System.debug(LoggingLevel.DEBUG, '---> query url ' + s);
            queryParams.add(s);
        }                
        if(!System.isFuture()) {
            System.debug(LoggingLevel.DEBUG, '---> processing One Degree service - start.');
            ServiceProviderClient.processOneDegreeService(authSet, queryParams);
            System.debug(LoggingLevel.DEBUG, '---> processing One Degree service - end.');            
        }
        if(!Test.isRunningTest()) {
        	// update metadata with last run date time stamp
        	attributeTags[0].Last_Run_Datetime__c = System.datetime.now();
        	String jobId2 = MetaDataUtility.upsertMetadata(attributeTags);                    
        }        

    }
}